version: "3"
services:
  #
  # API/Controller
  #
  api:
    image: issuer-kit-api:latest
    environment:
      - PORT=${API_PORT}
      - AGENT_ADMIN_URL=${ISSUER_ADMIN_URL}
      - AGENT_ADMIN_API_KEY=${ISSUER_ADMIN_API_KEY}
      - DB_SERVICE=${DB_SERVICE}
      - DB_NAME=${MONGODB_DATABASE}
      - DB_USER=${MONGODB_USER}
      - DB_PASSWORD=${MONGODB_PASSWORD}
      - DB_PORT=${MONGODB_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - EMAIL_SUBJECT=${EMAIL_SUBJECT}
      - PUBLIC_SITE_URL=${PUBLIC_SITE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - S2I_SCRIPTS_PATH=${S2I_SCRIPTS_PATH}
    volumes:
      - ./api/config:/opt/app-root/src/config
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - revo_load_test
    depends_on:
      - db
    command: >
      /bin/bash -c "
      echo waiting for database...;
      sleep 15;
      ${S2I_SCRIPTS_PATH}/run;"

  #
  # db
  #
  db:
    image: registry.access.redhat.com/rhscl/mongodb-36-rhel7
    environment:
      - MONGODB_ADMIN_PASSWORD=${MONGODB_ADMIN_PASSWORD}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - db-data:/var/lib/mongodb/data
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - revo_load_test

  #
  # issuer
  #
  issuer:
    image: aries-cloudagent:0.5.5-beta4
    environment:
      - LEDGER_URL=${LEDGER_URL}
      - WALLET_TYPE=${ISSUER_STORAGE_WALLET_TYPE}
      - POSTGRESQL_WALLET_HOST=${WALLET_HOST}
      - POSTGRESQL_WALLET_PORT=${WALLET_PORT}
      - POSTGRESQL_WALLET_USER=${WALLET_USER}
      - POSTGRESQL_WALLET_PASSWORD=${WALLET_PASSWORD}
      - POSTGRESQL_WALLET_ADMIN_PASSWORD=${WALLET_ADMIN_PASSWORD}
      - WALLET_ENCRYPTION_KEY=${ISSUER_WALLET_ENCRYPTION_KEY}
      - INDY_WALLET_SEED=${ISSUER_WALLET_SEED}
      - WEBHOOK_URL=${ISSUER_WEBHOOK_URL}
      - HTTP_INTERFACE_PORT=${ISSUER_HTTP_INTERFACE_PORT}
      - AGENT_ADMIN_PORT=${ISSUER_ADMIN_PORT}
      - AGENT_NAME=${ISSUER_NAME}
      - AGENT_ADMIN_API_KEY=${ISSUER_ADMIN_API_KEY}
      - TAILS_SERVER_URL=${TAILS_SERVER_URL}
    networks:
      - revo_load_test
    depends_on:
      - wallet
    # ports:
    #   - 8024:8024
    entrypoint: /bin/bash
    command: [
        "-c",
        "curl -d '{\"seed\":\"${ISSUER_WALLET_SEED}\", \"role\":\"TRUST_ANCHOR\", \"alias\":\"${ISSUER_NAME}\"}' -X POST ${LEDGER_URL}/register; \
        sleep 5; \
        aca-py start \
        --inbound-transport http '0.0.0.0' ${ISSUER_HTTP_INTERFACE_PORT} \
        --outbound-transport http \
        --endpoint ${ISSUER_ENDPOINT} \
        --genesis-url '${LEDGER_URL}/genesis' \
        --auto-accept-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-messages \
        --auto-store-credential \
        --auto-verify-presentation \
        --auto-respond-presentation-proposal \
        --wallet-type 'indy' \
        --wallet-name '${ISSUER_WALLET_NAME}' \
        --wallet-key '${ISSUER_WALLET_ENCRYPTION_KEY}' \
        --wallet-storage-type '${ISSUER_STORAGE_WALLET_TYPE}' \
        --wallet-storage-config '{\"url\":\"${WALLET_HOST}:${WALLET_PORT}\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${WALLET_USER}\",\"password\":\"${WALLET_PASSWORD}\",\"admin_account\":\"postgres\",\"admin_password\":\"${WALLET_ADMIN_PASSWORD}\"}' \
        --seed '${ISSUER_WALLET_SEED}' \
        --admin '0.0.0.0' ${ISSUER_ADMIN_PORT} \
        --${ISSUER_ADMIN_MODE} \
        --label ${ISSUER_NAME} \
        --log-level warning \
        --tails-server-base-url ${TAILS_SERVER_URL}",
      ]

  #
  # holder
  #
  holder:
    image: aries-cloudagent:0.5.5-beta4
    environment:
      - LEDGER_URL=${LEDGER_URL}
      - WALLET_TYPE=${HOLDER_STORAGE_WALLET_TYPE}
      - POSTGRESQL_WALLET_HOST=${WALLET_HOST}
      - POSTGRESQL_WALLET_PORT=${WALLET_PORT}
      - POSTGRESQL_WALLET_USER=${WALLET_USER}
      - POSTGRESQL_WALLET_PASSWORD=${WALLET_PASSWORD}
      - POSTGRESQL_WALLET_ADMIN_PASSWORD=${WALLET_ADMIN_PASSWORD}
      - WALLET_ENCRYPTION_KEY=${HOLDER_WALLET_ENCRYPTION_KEY}
      - INDY_WALLET_SEED=${HOLDER_WALLET_SEED}
      - WEBHOOK_URL=${HOLDER_WEBHOOK_URL}
      - HTTP_INTERFACE_PORT=${HOLDER_HTTP_INTERFACE_PORT}
      - AGENT_ADMIN_PORT=${HOLDER_ADMIN_PORT}
      - AGENT_NAME=${HOLDER_NAME}
      - AGENT_ADMIN_API_KEY=${HOLDER_ADMIN_API_KEY}
      - TAILS_SERVER_URL=${TAILS_SERVER_URL}
    networks:
      - revo_load_test
    depends_on:
      - wallet
    ports:
      - 8034:8034
    entrypoint: /bin/bash
    command: [
        "-c",
        "curl -d '{\"seed\":\"${HOLDER_WALLET_SEED}\", \"role\":\"TRUST_ANCHOR\", \"alias\":\"${HOLDER_NAME}\"}' -X POST ${LEDGER_URL}/register; \
        sleep 5; \
        aca-py start \
        --inbound-transport http '0.0.0.0' ${HOLDER_HTTP_INTERFACE_PORT} \
        --outbound-transport http \
        --endpoint ${HOLDER_ENDPOINT} \
        --genesis-url '${LEDGER_URL}/genesis' \
        --auto-accept-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-messages \
        --auto-respond-credential-offer \
        --auto-respond-presentation-request \
        --auto-respond-credential-request \
        --auto-verify-presentation \
        --wallet-type 'indy' \
        --wallet-name '${HOLDER_WALLET_NAME}' \
        --wallet-key '${HOLDER_WALLET_ENCRYPTION_KEY}' \
        --wallet-storage-type '${HOLDER_STORAGE_WALLET_TYPE}' \
        --wallet-storage-config '{\"url\":\"${WALLET_HOST}:${WALLET_PORT}\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${WALLET_USER}\",\"password\":\"${WALLET_PASSWORD}\",\"admin_account\":\"postgres\",\"admin_password\":\"${WALLET_ADMIN_PASSWORD}\"}' \
        --seed '${HOLDER_WALLET_SEED}' \
        --admin '0.0.0.0' ${HOLDER_ADMIN_PORT} \
        --${HOLDER_ADMIN_MODE} \
        --label ${HOLDER_NAME} \
        --tails-server-base-url ${TAILS_SERVER_URL}",
      ]

  #
  # wallet
  #
  wallet:
    image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest
    environment:
      - POSTGRESQL_USER=${WALLET_USER}
      - POSTGRESQL_PASSWORD=${WALLET_PASSWORD}
      - POSTGRESQL_DATABASE=${WALLET_DATABASE}
      - POSTGRESQL_ADMIN_PASSWORD=${WALLET_ADMIN_PASSWORD}
    networks:
      - revo_load_test
    ports:
      - ${WALLET_PORT}:${WALLET_PORT}
    volumes:
      - wallet-data:/var/lib/pgsql/data

  tails-server:
    build:
      context: https://github.com/bcgov/indy-tails-server.git
      dockerfile: docker/Dockerfile.tails-server
    ports:
      - ${TAILS_SERVER_PORT}:${TAILS_SERVER_PORT}
    volumes:
      - tails-storage:/tmp
    networks:
      - revo_load_test
    command: >
      tails-server
        --host 0.0.0.0
        --port $TAILS_SERVER_PORT
        --storage-path $TAILS_STORAGE_PATH
        --log-level $LOG_LEVEL

networks:
  revo_load_test:

volumes:
  wallet-data:
  db-data:
  tails-storage:
